/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kafka.demo.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum TransactionType implements org.apache.avro.generic.GenericEnumSymbol<TransactionType> {
  INSTANT_PAYMENT, SEPA, CREDIT_CARD  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TransactionType\",\"namespace\":\"com.kafka.demo.avro.model\",\"symbols\":[\"INSTANT_PAYMENT\",\"SEPA\",\"CREDIT_CARD\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
